title: Tender Blacklist ZA
description: A simple search tool / box driven by a single spreadsheet that allows users to check whether a person or company is blacklisted by local municipalities / provincial government / national treasury.

url: https://tenderblacklist-za.codeforafrica.org

google_analytics: G-L4FSSTW0R2
